### ISSUE TITLE
Chat icon

### ISSUE THREAD

**Issue by Zren** [Axel--/Naut-for-reddit#135]
I made my own icon for the spritesheet in /r/kde.

https://www.reddit.com/r/kde/about/stylesheet/#img-preview-spritesheet

1. I copied the 32x32 gray icon from [the reddit spritesheet](https://www.redditstatic.com/sprite-reddit.bTLvdEETokI.png).
2. I scaled it down to 14x14
3. I levelled the icon in GIMP so it's pure white (drag the white threshold grip all the way to black)
4. Copied the icon for the "active / have messages" icon
5. Set the regular icon to 65% opacity
6. Colorify the active icon to be orangered

My CSS:

```css
#chat {
    background-image: url(%%spritesheet%%);
    background-position: -1px -153px;
    background-size: 264px 264px;
}
#chat.active {
    background-position: -17px -153px;
}
```
