### ISSUE TITLE
RES 'Use subreddit style' input checkbox conflicting with popup

### ISSUE THREAD

**Issue by ncla** [Axel--/Naut-for-reddit#26]
![](http://puu.sh/geLsH/7c2ba0a735.png)

Sadly the RES styling is hardcoded inline and with !important rule everywhere.
![](http://puu.sh/geLwJ/ec4b928e1c.png)

**Comment by ncla** [comment]
Nevermind, the !important rule is not an issue, I fixed it like this:
```css
.morelink:after { 
    content: "Please remember to read the FAQ before creating a new post. Thank you!"; 
    z-index: 2147483647 !important; 
}
```
