### ISSUE TITLE
Consistent padding on active and inactive entries

### ISSUE THREAD

**Issue by razor-x** [Axel--/Naut-for-reddit#41]
Active entries have a blue border and extra padding. But this means they shift to the right when they are clicked on.

The main reason this is an issue is the preview buttons on RES. Say you click on the image preview button, then you click again without moving your mouse to close the preview. Since the content has all shifted to the right, your mouse cursor will (in most cases) no longer be on the button any more, so the preview will not close.

Adding the following will prevent the shift:

```css
.entry {
  padding-left: 8px !important;
  border-left: 2px solid rgba(0, 0, 0, 0);
}
``` 

You should also be able to remove the `padding-left` from the active entry selector as it will now be applied to all `.entry`.
