### ISSUE TITLE
Even left-border height on entries

### ISSUE THREAD

**Issue by razor-x** [Axel--/Naut-for-reddit#42]
The blue border for active entries extends uneven vertically. Adding this will keep the padding and margin consistent:

```css
.commentarea .entry {
  margin-bottom: 16px;
}

.res .commentarea .entry .flat-list {
  padding-bottom: 0;
}
```
