### ISSUE TITLE
Missing video expando icon on hover

### ISSUE THREAD

**Issue by synapsos** [Axel--/Naut-for-reddit#43]
The video expando icon does not show up in white on hover because of a typo in the background-position. This fixes it:
```css
.expando-button.video.collapsed:hover {background-position: -112px -32px !important;}
```
