### ISSUE TITLE
Expand button image not rendering properly on HiDPI screens

### ISSUE THREAD

**Issue by Yliaho** [Axel--/Naut-for-reddit#94]
To fix this, set ``background-size``to match the width of the spritesheet. Easy!

![expand button all sorts of fucked up](http://i.imgur.com/QYfoPoq.png)

**Comment by notderw** [comment]
Well dang I didn't know we could just set the background size to fix that, we will fix this in a future update.

Thanks!

**Comment by Yliaho** [comment]
Yup! It's because of this media query, reddit did when they updated the expand buttons:  
  
```CSS
@media only screen and (min-resolution: 2dppx), only screen and (-webkit-min-device-pixel-ratio: 2)
.expando-button.collapsed.selftext {
  /* ... */
  background-size: 23px 243px; /* <---- */
}
```  
  
Reddit has pushed for retina friendly spritesheets, and serves 2 variations of the expand buttons, thumbnails etc. You need to explicitly set the ``background-size`` of your custom spritesheets, otherwise it'll default to ``23px 243px``.  
  
You don't need to put in the both width and height -- width is just as fine.
